version: "2"

services:

  mongodb:
    image: mongo:3.4
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb-data:/data/db

  pushserver:
    build: ./
    ports:
      - 8000:8000
    depends_on:
      - mongodb

volumes:
  mongodb-data:
